name: Track TMDb Scores

on:
  schedule:
    - cron: '0 * * * *'  # Every hour on the hour
  workflow_dispatch:     # Manual trigger support

steps:
  - uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run tracker script
    run: python track_tmdb_scores.py

  # Optional: commit and push updates

jobs:
  track-scores:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run score tracker
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python track_tmdb_scores.py

      - name: Commit updated files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add tmdb_scores.csv index.html || true
          git commit -m "Update scores" || echo "No changes to commit"
          git push
